<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-26T17:18:26 GMT-04:00" name="AutomationTestSuite" finished-at="2024-09-26T17:19:02 GMT-04:00" duration-ms="35688">
    <groups>
      <group name="ErrorHandling">
        <method signature="Errorvalidation.checkOutWithOutCountry()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" name="checkOutWithOutCountry" class="yashwanthgunapatiqa.tests.Errorvalidation"/>
        <method signature="Errorvalidation.loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" name="loginErrorValidation" class="yashwanthgunapatiqa.tests.Errorvalidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-09-26T17:18:26 GMT-04:00" name="Error Handling Test" finished-at="2024-09-26T17:19:02 GMT-04:00" duration-ms="35688">
      <class name="yashwanthgunapatiqa.tests.Errorvalidation">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:26 GMT-04:00" name="LaunchBrowser" finished-at="2024-09-26T17:18:35 GMT-04:00" duration-ms="8437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="checkOutWithOutCountry()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:35 GMT-04:00" name="checkOutWithOutCountry" finished-at="2024-09-26T17:18:43 GMT-04:00" duration-ms="8515" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please Enter Full Shipping Information] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please Enter Full Shipping Information] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at yashwanthgunapatiqa.tests.Errorvalidation.checkOutWithOutCountry(Errorvalidation.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOutWithOutCountry -->
        <test-method is-config="true" signature="closeWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:44 GMT-04:00" name="closeWebSite" finished-at="2024-09-26T17:18:44 GMT-04:00" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebSite -->
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:44 GMT-04:00" name="LaunchBrowser" finished-at="2024-09-26T17:18:51 GMT-04:00" duration-ms="6717" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:51 GMT-04:00" name="loginErrorValidation" finished-at="2024-09-26T17:18:53 GMT-04:00" duration-ms="1929" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at yashwanthgunapatiqa.tests.Errorvalidation.loginErrorValidation(Errorvalidation.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="closeWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:53 GMT-04:00" name="closeWebSite" finished-at="2024-09-26T17:18:53 GMT-04:00" duration-ms="342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebSite -->
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:18:53 GMT-04:00" name="LaunchBrowser" finished-at="2024-09-26T17:19:00 GMT-04:00" duration-ms="6992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:19:00 GMT-04:00" name="loginErrorValidation" finished-at="2024-09-26T17:19:01 GMT-04:00" duration-ms="1298" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at yashwanthgunapatiqa.tests.Errorvalidation.loginErrorValidation(Errorvalidation.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="closeWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@35432107]" started-at="2024-09-26T17:19:02 GMT-04:00" name="closeWebSite" finished-at="2024-09-26T17:19:02 GMT-04:00" duration-ms="204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebSite -->
      </class> <!-- yashwanthgunapatiqa.tests.Errorvalidation -->
    </test> <!-- Error Handling Test -->
  </suite> <!-- AutomationTestSuite -->
</testng-results>
